API_VERSION = "1.0"

HTTP_SERVER_IP = "127.0.0.1"
HTTP_SERVER_PORT = 5000

API_NAME = "api"
RESOURCE_GET_RESPONSE = "getResponse"
RESOURCE_POST_ADDRESSES = "postAddresses"

URI_GET_RESPONSE = f"/{API_NAME}/{API_VERSION}/{RESOURCE_GET_RESPONSE}"
URI_POST_ADDRESSES = f"/{API_NAME}/{API_VERSION}/{RESOURCE_POST_ADDRESSES}"
